### PR TITLE
fixing opening character ('<' instead of '>') for pairs of angle brackets

### PR DESCRIPTION
**Pull request by hpcbjdic**
dto

### CODE REVIEW

**Comment by briandoll** [comment]
Great catch! Thanks so much!

**Comment by briandoll** [comment]
Had to revert this. The reason the starting character for HTML tags (or any bracket-oriented tag) is `>` and not `<` is that the goal of this plugin is to change _inside_ the surroundings, which in this case is the tag. We're not changing the tag itself, we're changing what's inside it. 

Eg. `<div class="header">header text | here</div>`

If our cursor is the vertical bar between the words "text" and "here", I want this plugin to remove "header text here", so we can replace that text. The "start" of that search ends when the div tag ends, with the `>` character.

Hope that helps, and thanks for the suggestion!

**Comment by hpcbjdic** [comment]
Oh, yes. Sorry, I forgot to think about HTML and XML stuff.
However, is it possible to distinguish between different languages here? In C++, e.g., it would be great to be able to change everything between '<' and '>' as those characters are used to pass template parameters while the section between '>' and '<' has no special meaning.

**Comment by briandoll** [comment]
Ah! Yeah, that would be nice. I wonder if there is a way for vim to source local configuration options, and append that local list to the `surrounding_beginnings` variable here?

**Pull request merged**
